Animal Spawning and Respawning
2401lucas/Project-Alpha pull request #63
Opened 2021-05-13 14:12 UTC by JaredTrenholm

2021-05-13 14:27 UTC, 2401lucas requested changes
AnimalManager: 
Remove Update and put coroutine in place (With 1 second delay approx)
Have a bool to use respawning
No Overlap sphere, Use hashtable instead to save relation of checkpoint/respawn timer
Remove InitialSpawn
One Animal, set the mesh filter and renderer to the animal you want, tell the animal what kind of animal it is 
Start with only small animals, then some medium, then some large, then no small, then no medium. Animal choice is based on random chance IE 75% for small, 20% for medium, 5% Large

2021-05-14 14:22 UTC, 2401lucas requested changes

2021-05-14 14:22 UTC, 2401lucas commented on Assets/Scripts/Managers/AnimalManager.cs
> +        public bool canRespawn = false;
Should be useRespawn

2021-05-14 14:22 UTC, 2401lucas commented on Assets/Scripts/Managers/AnimalManager.cs
> +        public void StartManager()
Should Also clear the Job table

2021-05-14 14:22 UTC, 2401lucas commented on Assets/Scripts/Managers/AnimalManager.cs
> +        private Hashtable animalSpawns = new Hashtable();
Hashtable should contain all checkpoints and respawn timers on checkpoints with no animals. If the checkpoint has an actively spawned animal, we do not want it in the hashtable.

2021-05-14 14:22 UTC, 2401lucas commented on Assets/Scripts/Managers/AnimalManager.cs
> +        private bool CanSpawn()
Can spawn should not contain an if statement, it should simply return  the condition

2021-05-14 14:22 UTC, 2401lucas commented on Assets/Scripts/Managers/AnimalManager.cs
> +            float animalResult = UnityEngine.Random.Range(0, 101);
The upper value of range should be the sum of the percentages of the animal spawn chances

2021-07-05 21:55 UTC, SirLorrence approved these changes
Everything seems to be in order.

2021-07-05 21:59 UTC, merged